(cl:defpackage e2e_hpc-msg
  (:use )
  (:export
   "<CUSTOMMSG_CONNECTION>"
   "CUSTOMMSG_CONNECTION"
   "<CUSTOMMSG_DOOR>"
   "CUSTOMMSG_DOOR"
   "<CUSTOMMSG_RSSI>"
   "CUSTOMMSG_RSSI"
   "<CUSTOMMSG_RANGING>"
   "CUSTOMMSG_RANGING"
  ))

