// Generated by gencpp from file e2e_hpc/DisAoaRequest.msg
// DO NOT EDIT!


#ifndef E2E_HPC_MESSAGE_DISAOAREQUEST_H
#define E2E_HPC_MESSAGE_DISAOAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace e2e_hpc
{
template <class ContainerAllocator>
struct DisAoaRequest_
{
  typedef DisAoaRequest_<ContainerAllocator> Type;

  DisAoaRequest_()
    : Distance(0.0)
    , AoA(0.0)  {
    }
  DisAoaRequest_(const ContainerAllocator& _alloc)
    : Distance(0.0)
    , AoA(0.0)  {
  (void)_alloc;
    }



   typedef double _Distance_type;
  _Distance_type Distance;

   typedef double _AoA_type;
  _AoA_type AoA;





  typedef boost::shared_ptr< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DisAoaRequest_

typedef ::e2e_hpc::DisAoaRequest_<std::allocator<void> > DisAoaRequest;

typedef boost::shared_ptr< ::e2e_hpc::DisAoaRequest > DisAoaRequestPtr;
typedef boost::shared_ptr< ::e2e_hpc::DisAoaRequest const> DisAoaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::e2e_hpc::DisAoaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::e2e_hpc::DisAoaRequest_<ContainerAllocator1> & lhs, const ::e2e_hpc::DisAoaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Distance == rhs.Distance &&
    lhs.AoA == rhs.AoA;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::e2e_hpc::DisAoaRequest_<ContainerAllocator1> & lhs, const ::e2e_hpc::DisAoaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace e2e_hpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdd62682e37010cc81e982ba74365e59";
  }

  static const char* value(const ::e2e_hpc::DisAoaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdd62682e37010ccULL;
  static const uint64_t static_value2 = 0x81e982ba74365e59ULL;
};

template<class ContainerAllocator>
struct DataType< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2e_hpc/DisAoaRequest";
  }

  static const char* value(const ::e2e_hpc::DisAoaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Distance\n"
"float64 AoA\n"
"\n"
;
  }

  static const char* value(const ::e2e_hpc::DisAoaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Distance);
      stream.next(m.AoA);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DisAoaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::e2e_hpc::DisAoaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::e2e_hpc::DisAoaRequest_<ContainerAllocator>& v)
  {
    s << indent << "Distance: ";
    Printer<double>::stream(s, indent + "  ", v.Distance);
    s << indent << "AoA: ";
    Printer<double>::stream(s, indent + "  ", v.AoA);
  }
};

} // namespace message_operations
} // namespace ros

#endif // E2E_HPC_MESSAGE_DISAOAREQUEST_H
