// Generated by gencpp from file e2e_hpc/DisAoa.msg
// DO NOT EDIT!


#ifndef E2E_HPC_MESSAGE_DISAOA_H
#define E2E_HPC_MESSAGE_DISAOA_H

#include <ros/service_traits.h>


#include <e2e_hpc/DisAoaRequest.h>
#include <e2e_hpc/DisAoaResponse.h>


namespace e2e_hpc
{

struct DisAoa
{

typedef DisAoaRequest Request;
typedef DisAoaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisAoa
} // namespace e2e_hpc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::e2e_hpc::DisAoa > {
  static const char* value()
  {
    return "1333d23ef3de7dce5e31068bfe611dd5";
  }

  static const char* value(const ::e2e_hpc::DisAoa&) { return value(); }
};

template<>
struct DataType< ::e2e_hpc::DisAoa > {
  static const char* value()
  {
    return "e2e_hpc/DisAoa";
  }

  static const char* value(const ::e2e_hpc::DisAoa&) { return value(); }
};


// service_traits::MD5Sum< ::e2e_hpc::DisAoaRequest> should match
// service_traits::MD5Sum< ::e2e_hpc::DisAoa >
template<>
struct MD5Sum< ::e2e_hpc::DisAoaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::e2e_hpc::DisAoa >::value();
  }
  static const char* value(const ::e2e_hpc::DisAoaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::e2e_hpc::DisAoaRequest> should match
// service_traits::DataType< ::e2e_hpc::DisAoa >
template<>
struct DataType< ::e2e_hpc::DisAoaRequest>
{
  static const char* value()
  {
    return DataType< ::e2e_hpc::DisAoa >::value();
  }
  static const char* value(const ::e2e_hpc::DisAoaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::e2e_hpc::DisAoaResponse> should match
// service_traits::MD5Sum< ::e2e_hpc::DisAoa >
template<>
struct MD5Sum< ::e2e_hpc::DisAoaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::e2e_hpc::DisAoa >::value();
  }
  static const char* value(const ::e2e_hpc::DisAoaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::e2e_hpc::DisAoaResponse> should match
// service_traits::DataType< ::e2e_hpc::DisAoa >
template<>
struct DataType< ::e2e_hpc::DisAoaResponse>
{
  static const char* value()
  {
    return DataType< ::e2e_hpc::DisAoa >::value();
  }
  static const char* value(const ::e2e_hpc::DisAoaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // E2E_HPC_MESSAGE_DISAOA_H
